### ISSUE TITLE
If a slot is reused, only the last reference appears in the output

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolinkml#106]
``` 
   classes:
       c1:
         slots:
            - s1
      c2:
        slots:
            - s1
```
S1 only shows on C2 in generated pythong
