### ISSUE TITLE
Mismatch between the model and the generated JSON Schema

### ISSUE THREAD

**Issue by deepakunni3** [biolink/biolinkml#108]
YAML:

```yaml
  biosample:
    is_a: named thing
    aliases: ['sample', 'material sample']
    description: >-
      A material sample. It may be environmental (encompassing many organisms) or isolate or tissue.  
      An environmental sample containing genetic material from multiple individuals is commonly referred to as a biosample.  
    slots:
      - annotations
    slot_usage:
      id:
        description: >-
          The primary identifier for the biosample
      name:
        description: >-
          A human readable name or description of the biosample
      alternate identifiers:
        description: >-
          The same biosample may have distinct identifiers in different databases (e.g. GOLD and EMSL)
      annotations:
        range: annotation
```

Generated JSON Schema:
```json
      "Biosample": {
         "description": "A material sample. It may be environmental (encompassing many organisms) or isolate or tissue.   An environmental sample containing genetic material from multiple individuals is commonly referred to as a biosample.",
         "properties": {
            "alternate_identifiers": {
               "items": {
                  "type": "string"
               },
               "type": "array"
            },
            "annotations": {
               "items": {
                  "type": "string"
               },
               "type": "array"
            },
            "id": {
               "type": "string"
            },
            "name": {
               "type": "string"
            }
         },
         "title": "Biosample",
         "type": "object"
      },
```

In case of `annotations` property, the items should be of type `object` instead of `string`.

As of now, validation via JSON Schema fails because while the data is correct, in terms of modeling, there is a mismatch between the model and the generated JSON schema.
