### ISSUE TITLE
Add reversible to_str meta-property

### ISSUE THREAD

**Issue by cmungall** [biolink/biolinkml#128]
Use case: lat-long coordinates can be represented in both structured/normalized and flattened/denormalized form. E.g

```yaml
  geolocation value:
    is_a: attribute value
    description: >-
      A normalized value for a location on the earth's surface
    slots:
      - latitude
      - longitude
      - as string value
    slot_usage:
      as string value:
        to_str: "{latitude} {longitude}"
```

The semantics of SLOT.to_str would be:

 - the range of SLOT must be string
 - the value of SLOT must be equal to to_str, expanding all `{x}` expressions with SLOT.parent.x

Implementations are not dictated but for python way to generate code for _as_str.

This could be used to drive validators and bidirectional converters (e.g. given a flat string, auto-parse into normalized object)

**Comment by cmungall** [comment]
Adding some notes to clarify the use case for string_serialization as a slot property

#301 has serialization/parsing for the canonical serialization for a class, which is great, but it can also be useful at the slot level

Consider

```
classes:
  person:
     slot_usage:
       firstname:
       lastname:
       fullname:
         description: "E.g. Chris Mungall"
         string_serialization: "{firstname} {lastname}"
       phonebook_entry:
         description: "E.g. Mungall, Chris"
         string_serialization: "{lastname}, {firstname}"
       journal_entry:
         description: "E.g. Mungall, C"
         string_serialization: "{lastname}, {firstname}[0;1]"
    string_template: "{firstname} {lastname}"
```

(the journal_entry be out of bounds for expressivity but just adding for illustrative purposes)

The class level string_template may be redundant with the canonical `fullname` but I think that is OK

The main point is that it's useful to have different serializations for a slot

In all cases, the interpolation is evaluated at the level of the containing class instance
