### ISSUE TITLE
Design patterns for handling measurement properties

### ISSUE THREAD

**Issue by cmungall** [biolink/biolinkml#159]
I see two general patterns in templates/schemas/checklists for dealing with quantitative properties (slots) such as `depth`

 1. A general property such as `depth`, allow specification of booth value and a unit
 2. Bake in the unit into the property, e.g. `depth_in_meters`, and allow only a number as range

For simplicity I am omitting reified models etc

An anti-pattern is a field name such as `depth` where the unit is *implicit*, this has obvious issues

For 1, there are a number of variants:

 - the range of the property is a string, with a syntax defined by regex or grammar, e.g. "{value} {unit}"
 - the range of the property is an object, which has its own properties, e.g. `unit` and `value`

Note these are not mutually exclusive. E.g. in the NMDC schema properties have objects as value, these have both a raw-value property, and normalized properties, see [QuantityValue](https://microbiomedata.github.io/nmdc-metadata/docs/QuantityValue.html)

Note also that 2 affords extra flexibility, e.g. if we want to add precision, or provenance, it is trivial to extend

I think the modeling patterns for 2 are relatively clear. For 1, how should we indicate the unit?

Of course, saying `depth_in_meters` is obvious to a human, but how do we formalize this?

One way would be to make quantities first class members in the metamodel and encode this directly with a unit metaproperty, e.g.

```
slots:
  depth_in_meters:
     is_a: depth.   ## optional
     unit: m
```

another option is to make the metamodel more neutral, and define types for use in measurement domains, e.g.

```
types:
  meter_value:
    description: "used for "
    uri: xsd:double
    base: double
    mappings:
      - UO:123456 ## meter

...

slots:
  depth_in_meters:
    range: meter_value
```

this makes things a little more explicit but we don't really have a formal binding

in either case, the underlying semantics at the rdf/json-ld level should be:

```
?i depth_in_U ?v
<->
?i depth [
   unit: U
   value: ?v
]
```
