### ISSUE TITLE
Documentation generation has odd results (domain inducement resurfacing?)

### ISSUE THREAD

**Issue by cmungall** [biolink/biolinkml#178]
See https://cmungall.github.io/dasher/MetricResult.html

```
Inherited from download problem:
has source OPT
range: KnowledgeSource

Inherited from problem:
description OPT
Description: A description
range: String
```

but this class does not inherit from anything!

This is once again a resurfacing of the error where slots had induced domains; in this case has_source

```
 metric result:
    description: >-
      Result of executing a metric on a KS
    slots:
      - evaluated using
      - has source
      - has status
      - description
      - has messages

  problem:
    description: >-
      An object representing an error or problem encountered
    slots:
      - description

  download problem:
    is_a: problem
    description: >-
      A problem in downloading a knowledge source
    slots:
      - has source
```
