### ISSUE TITLE
Slot_usage is not reflected in identifier class

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolinkml#201]
If you specialize the type of a class or slot name:
```yaml
classes:
   schema_definition:
           is_a: element
           ...
          slot_usage:
            name:
                range: ncname
```

This is not reflected in the generated python:
```python
class SchemaDefinitionName(ElementName):
    pass
```
It should be:
```python
class SchemaDefinitionName(NCName):
    pass
```
