### ISSUE TITLE
Error diagnosis for malformed class is difficult to understand

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolinkml#268]
```yaml
classes:
    MapVersion:
          this is some text
```
Produces a cryptic error message
