### ISSUE TITLE
symmetry and inverse characteristics are not translated in OWL

### ISSUE THREAD

**Issue by cmungall** [biolink/biolinkml#290]
```yaml
id: http://example.org/tests/issue63

classes:
  c:

slots:
  s:
    inverse: t
    symmetric: true
    range: c

  t:
    range: c
```

gen-owl makes

```
<http://example.org/tests/issue63/s> a owl:ObjectProperty,
        meta:SlotDefinition ;
    rdfs:label "s" ;
    rdfs:domain <http://example.org/tests/issue63/C> ;
    rdfs:range <http://example.org/tests/issue63/C> .
```

(aside: I see if infers the domain, nice)
