### ISSUE TITLE
biolinkml optional slots populated in object

### ISSUE THREAD

**Issue by wdduncan** [biolink/biolinkml#296]
When I create an object according to the specifications in the yaml file, the optional slots (i.e., required: false) still show up as part of the object.

For example, in the [nmdc schema](https://github.com/microbiomedata/nmdc-metadata/schema/), the class `named thing` is specified like so:
```yaml
named thing:
    description: "a databased entity or concept/class"
    abstract: true
    slots:
      - id
      - name
      - description
      - alternate identifiers
```
The `alternative identifiers` slots is specified like this:
```yaml
alternate identifiers:
    aliases: ['mappings', 'alt ids', 'xrefs']
    description: >-
      Non-primary identifiers
    multivalued: true
    range: string
    required: false
```
Suppose, I create an instance of named thing using this code:
```python
In [3]: import nmdc
In [5]: n1 = nmdc.NamedThing(id='id:1',  name='object 1', description='test for named thing')
In [6]: n1
Out[6]: NamedThing(id='id:1', name='object 1', description='test for named thing', alternate_identifiers=[])
```
When I view the object, the alternative identifiers slot still shows up:
```python
alternate_identifiers=[]
```
Do we want this slot to still be included in the instantiated object? I'm having to filter out the empty alternative identifier list when converting to a dict. E.g.:
```python
In [4]: import jsonasobj
In [8]: jsonasobj.as_dict(n1)
Out[8]: 
{'id': 'id:1',
 'name': 'object 1',
 'description': 'test for named thing',
 'alternate_identifiers': []}
```
