### ISSUE TITLE
biolinkml None slots populated in object

### ISSUE THREAD

**Issue by wdduncan** [biolink/biolinkml#297]
This is similar to #296 but pertains to the value `None` showing up in the objects.  

In the [nmdc schema](https://github.com/microbiomedata/nmdc-metadata/schema/), the class `named thing` is specified like so:
```yaml
named thing:
    description: "a databased entity or concept/class"
    abstract: true
    slots:
      - id
      - name
      - description
      - alternate identifiers
```
If I create a simple object like so:
```python
In [1]: import nmdc
In [2]: n1 = nmdc.NamedThing(id='id:1',  name='object 1')
```
The `description` slot has the value `None`:
```python
In [3]: n1
Out[3]: NamedThing(id='id:1', name='object 1', description=None, alternate_identifiers=[])
```
This results in null values being saved when serializing the object as json. E.g.:
```python
In [5]: with open('test-dump.json', 'w') as f:
    ...:     json.dump(n1.__dict__, f)
```
produces:
```json
{"id": "id:1", "name": "object 1", "description": null, "alternate_identifiers": []}
```
Do we want remove the `null` valued slots? That is, produce the output:
```json
{"id": "id:1", "name": "object 1"}
```
