### ISSUE TITLE
mixup date vs datetime

### ISSUE THREAD

**Issue by VladimirAlexiev** [biolink/biolinkml#3]
https://github.com/biolink/biolinkml/blob/master/includes/types.yaml#L59:
```yaml
  date:
    uri: xsd:dateTime
    base: XSDDateTime
  datetime:
    uri: xsd:dateTime
    base: XSDDate
```

It seems to me that the `base` (python mappings) are reversed?
