### ISSUE TITLE
alt_description not behaving as expected

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolinkml#326]
The following:
```yaml
id: https://hotecosystem.org/tccm/datatype
name: datatypes
alt_descriptions:
  - source: UMLInfrastructure2.3,p.100
    text: a type whose instances are identified only by their value
```

Should fail because alt_description has no `text` parameter.  It errors out for an entirely bogus reason

```yaml
id: https://hotecosystem.org/tccm/datatype
name: datatypes
alt_descriptions:
  - source: UMLInfrastructure2.3,p.100
    description: a type whose instances are identified only by their value
```

Should pass, but it fails because `source` is type NCName -- we need to decide whether we expect a URI/Curie in the source field or a string.  (For the moment I'd propose `string`)
