### ISSUE TITLE
allow mappings on enum values

### ISSUE THREAD

**Issue by cmungall** [biolink/biolinkml#362]
I would like be able to include mappings on enum values, e.g

```yaml
enums:
  strand_enum:
    description: strand
    permissible_values:
      "+":
        description: Positive
        close_mappings:
          - faldo:ForwardStrandPosition
      "-":
        description: Negative
        close_mappings:
          - faldo:ReverseStrandPosition
      ".":
        description: Unstranded
        close_mappings:
          - faldo:BothStrandsPosition
      "?":
        description: Unknown
```
