### ISSUE TITLE
enums are not imported in generated python code

### ISSUE THREAD

**Issue by cmungall** [biolink/biolinkml#368]
E.g

```yaml
id: https://microbiomedata/schema

prefixes:
  biolinkml: https://w3id.org/biolink/biolinkml/

imports:
  - biolinkml:types
  - issues_368_imports

classes:

  c:
    is_a: parent_class
    slots:
      - s

slots:
  s:
    range: e
```

where the imported file is:

```yaml
id: https://microbiomedata/schema/mixs

classes:
  parent_class: {}

enums:
  e:
    permissible_values:
      a: A
      b: B
```

```bash
$ gen-python --no-mergeimports tests/test_issues/input/issue_368.yaml
```

makes:

```python
...
from . issues_368_imports import ParentClass
...
```

but the python should also import `E`
