### ISSUE TITLE
gen-jsonld-context fails to generate entries if default prefix is specified

### ISSUE THREAD

**Issue by cmungall** [biolink/biolinkml#378]
**Describe the bug**

normally gen-jsonld-context makes an entry for each slot

however, if there is a default_prefix declared in the schema AND the slot lacks a slot_uri, THEN no entry is created

This originated from investigating biolink/biolinkml#377  

**To Reproduce**

no default prefix
```yaml
id: http://example.org/sssom/schema/
name: sssom
imports:
- biolinkml:types
prefixes:
  biolinkml: https://w3id.org/biolink/biolinkml/
  sssom: https://w3id.org/sssom/
  dcterms: http://purl.org/dc/terms/
default_curi_maps:
- semweb_context

slots:
  name:
    range: string
```

makes

```json
{
   "_comments": "Auto generated from test.yaml by jsonldcontextgen.py version: 0.1.1\nGeneration date: 2021-01-07 12:08\nSchema: sssom\n\nid: http://example.org/sssom/schema/\ndescription: \nlicense: https://creativecommons.org/publicdomain/zero/1.0/\n",
   "@context": {
      "type": "@type",
      "biolinkml": "https://w3id.org/biolink/biolinkml/",
      "dcterms": "http://purl.org/dc/terms/",
      "sssom": "https://w3id.org/sssom/",
      "@vocab": "http://example.org/sssom/schema/",
      "name": {
         "@id": "http://example.org/sssom/schema/name"
      }
   }
}
```

this includes `name` as expected, with the expected mapping to a URI. All good

However, if we add default_prefix:

```yaml
id: http://example.org/sssom/schema/
name: sssom
imports:
- biolinkml:types
prefixes:
  biolinkml: https://w3id.org/biolink/biolinkml/
  sssom: https://w3id.org/sssom/
  dcterms: http://purl.org/dc/terms/
default_curi_maps:
- semweb_context
default_prefix: sssom

slots:
  name:
    range: string
```

then the name entry disappears:

```json
{
   "_comments": "Auto generated from test.yaml by jsonldcontextgen.py version: 0.1.1\nGeneration date: 2021-01-07 12:09\nSchema: sssom\n\nid: http://example.org/sssom/schema/\ndescription: \nlicense: https://creativecommons.org/publicdomain/zero/1.0/\n",
   "@context": {
      "type": "@type",
      "biolinkml": "https://w3id.org/biolink/biolinkml/",
      "dcterms": "http://purl.org/dc/terms/",
      "sssom": "https://w3id.org/sssom/",
      "@vocab": "https://w3id.org/sssom/"
   }
}
```

this is presumably not intentional. Note it means that if I have `name` in my jsonld, then no rdf will be made from it
