### ISSUE TITLE
enums: allow meanings slot to have multiple values

### ISSUE THREAD

**Issue by wdduncan** [biolink/biolinkml#388]
From LinkML meeting on 02/26/2006

I some cases the `meaning` of an enum may map to multiple ontology terms. E.g., SNOMED and NCIT both have URIs for the same (lexically speaking) cancer. We may want to have ability to specify both the SNOMED and NCIT `meaning` of the enum.

Also (perhaps), we may wish to pair the URI with a gloss of the meaning. E.g.:
```
enum:
  tooth_enum:
    1:
     description: upper right third molar
    meaning: UBERON:0018577, FMA:55813, wisdom tooth
```
cc @hsolbrig @cmungall @deepakunni3 @sierra-moxon
