### ISSUE TITLE
shex: uri is not the same as NONLITERAL

### ISSUE THREAD

**Issue by VladimirAlexiev** [biolink/biolinkml#4]
This builtin type
```yaml
  uri:
    uri: xsd:anyURI
    base: URI
    repr: str
    description: a complete URI
```
gets mapped to this shex:
```
<Uri> NONLITERAL
```

However, I believe `NONLITERAL` includes blank nodes. `uri` should not allow blank nodes, according to its description
