### ISSUE TITLE
Add URI function to ifabsent options

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolinkml#41]
We need to be able to default the various elements of an Association to default values.  As an example, for a correlation association, we may way to say:

```
    slot_usage:
      relation:
        subproperty_of: NCIt:C48834
        ifabsent: URI(NCIt:C48834)
```
