### ISSUE TITLE
Code generation wrong for multiples

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolinkml#44]
biolinkml version 1.4.4 takes

```yaml
category:
    is_a: node property
    domain: named thing
    range: iri type
    description: >-
      Name of the high level ontology class in which this entity is categorized. Corresponds to the label for the biolink entity type class.
      In a neo4j database this MAY correspond to the neo4j label tag
    is_class_field: true
    multivalued: true
    in_subset:
      - translator_minimal
    required: true
    slot_uri: rdfs:subClassOf
```
and generates:

```python
@dataclass
class NamedThing(YAMLRoot):
    """
    a databased entity or concept/class
    """
   [snip]
    id: Union[str, NamedThingId]
    name: Union[str, LabelType]
    category: List[Union[str, IriType]] = empty_list()

    def __post_init__(self):
        if not isinstance(self.id, NamedThingId):
            self.id = NamedThingId(self.id)
        if not isinstance(self.name, LabelType):
            self.name = LabelType(self.name)
        if not isinstance(self.category, IriType):     <- This is wrong - it should be testing against a list
            self.category = IriType(self.category)
        super().__post_init__()
```
