### ISSUE TITLE
drug is declared as a slot

### ISSUE THREAD

**Issue by cmungall** [biolink/biolinkml#52]
```
  drug exposure:
    aliases: ['drug intake', 'drug dose']
    is_a: environment
    description: >-
      A drug exposure is an intake of a particular chemical substance
#    slots:
#      - has input
    slot_usage:
      drug:
        range: chemical substance
        required: true
        multivalued: true
    class_uri: ECTO:0000509
    mappings:
      - SIO:001005
```
