### ISSUE TITLE
Domain of slot should match any declaring subclass

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolinkml#56]
The following should pass:
```
slots:
    s1:
      domain: c1

classes:
     c1:
     c2:
          is_a: c1
          slots:
             - s1
```
