### ISSUE TITLE
shex: how to emit the defined prefixes?

### ISSUE THREAD

**Issue by VladimirAlexiev** [biolink/biolinkml#6]
This schema:
```yaml
id: https://example.com/schema

prefixes:
  dct:  http://purl.org/dc/terms/

emit_prefixes:
  - dct  

id_prefixes:
  - dct  

imports: [types]
default_range: string

slots:
  dct:created: {range: datetime}  # slot_uri: "dct:created"

classes:
  Company:
    slots:
    - dct:created              
```
generates this shex:
```
BASE <https://example.com/schema/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
<Datetime> xsd:dateTime
<Company> EXTRA rdf:type CLOSED {
    $<Company_t> <dct:created> @<Datetime> ?
}
```
The URL in the last line resolves to `https://example.com/schema/dct:created`, which is obviously not what I need. I have to enter `slot_uri` to get what I need (see commented line above).
Isn't there an easier way? What are `emit_prefixes` and `id_prefixes` for?

**Comment by hsolbrig** [comment]
The format above is an error -- you can't use prefixes on slot names.  I updated the language to detect this issue.  The way to say what you are trying to say above is:

```
slots:
    created: {range: datetime, slot_uri: dct:created}
...
classes:
    Company:
       slots:
          - created
```
(See: [tests/test_issues/source/Issue_6_fixed.yaml](https://github.com/biolink/biolinkml/blob/master/tests/test_issues/source/Issue_6_fixed.yaml))
