### ISSUE TITLE
Specifying a class uri

### ISSUE THREAD

**Issue by wdduncan** [biolink/biolinkml#80]
Consider the following class defined in yaml:
```
classes:
    person:
        description: A person, living or dead
        slots:
            - id
```

How do I specify an IRI for the class person? I've tried this:
```
classes:
    person:
        description: A person, living or dead
        class_uri: http://example.com/10001
        slots:
            - id: http://example.com/10001 # error
```
But I get an error: `File: None Class "person" - unknown slot: "{'id': 'http://example.com/10001'}"`

I've also tried using `class_uri` like this:
```
   person:
        description: A person, living or dead
        class_uri: http://example.com/10001
        slots:
            - id
```

but the json-ld output is not quite right:
```
"classes": [
    {
      "name": "Person",
      "mappings": [
        "http://example.com/10001"
      ],
      "description": "A person, living or dead",
      "from_schema": "http://example.org/sample/example1",
      "slots": [
        "id"
      ],
      "class_uri": "http://example.com/10001",
      "type": "ClassDefinition"
    }
  ]
```
It should look something like:
```
{
  "@contex": { .... },
  {
     "@id": "http://example.com/10001",
     "@type": "owl:Class"
   }
}
```
